#!/bin/bash

#拉取git clone源码
git clone --depth 1 --single-branch https://github.com/LiBwrt-op/openwrt-6.x.git libwrt

#进入编译路径
cd libwrt

#二次编译
git fetch && git reset --hard origin/k6.12-nss

#添加rtp2httpd进feeds
src-git rtp2httpd https://github.com/stackia/rtp2httpd.git

#更新feeds
./scripts/feeds update -a && ./scripts/feeds install -a

#更新agronv3主题
rm -rf feeds/luci/themes/luci-theme-argon
git clone https://github.com/jerrykuku/luci-theme-argon.git feeds/luci/themes/luci-theme-argon

#修改默认主题为agronv3
#feeds/luci/collections/luci-light/Makefile，删除bootstrap行
#feeds/luci/collections/luci-nginx/Makefile，删除bootstrap行

#更新ddns-go
rm -rf feeds/packages/net/ddns-go
rm -rf feeds/luci/applications/luci-app-ddns-go
git clone https://github.com/sirpdboy/luci-app-ddns-go
mv luci-app-ddns-go/luci-app-ddns-go feeds/luci/applications/luci-app-ddns-go
mv luci-app-ddns-go/ddns-go feeds/packages/net/ddns-go
rm -rf luci-app-ddns-go

#更新集客AC
rm -rf feeds/luci/applications/luci-app-gecoosac
rm -rf feeds/packages/net/gecoosac
git clone https://github.com/lwb1978/openwrt-gecoosac
mv openwrt-gecoosac/luci-app-gecoosac feeds/luci/applications/luci-app-gecoosac
mv openwrt-gecoosac/gecoosac feeds/packages/net/gecoosac
rm -rf openwrt-gecoosac


rm -rf ./tmp

#更新luci和packages
./scripts/feeds update -i packages
./scripts/feeds install -a -p packages
./scripts/feeds update -i luci
./scripts/feeds install -a -p luci

#下载自己的默认配置
rm -rf .config
curl -sfL https://raw.githubusercontent.com/tangyl2000/zn-m2/main/zn-m2-config-hxlls -o .config

make menuconfig
make defconfig

make download -j8

make -j8 V=s
